# Generated by Django 3.0.2 on 2020-01-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDSubject', models.IntegerField()),
                ('AGE', models.IntegerField()),
                ('SPORT', models.IntegerField()),
                ('label', models.FloatField()),
                ('xchest', models.FloatField()),
                ('ychest', models.FloatField()),
                ('zchest', models.FloatField()),
                ('ecg', models.FloatField()),
                ('resp', models.FloatField()),
                ('xwrist', models.FloatField()),
                ('ywrist', models.FloatField()),
                ('zwrist', models.FloatField()),
                ('bvp', models.FloatField()),
                ('temp', models.FloatField()),
                ('activity', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
